### ISSUE TITLE
Channel names can not contain spaces

### ISSUE THREAD

**Issue by mgbckr** [KyleFerchen/pyInfinityFlow#1]
Hi,

it seems that spaces are automatically removed from channel names by the `FCSFileObject`. Consequently, a channel with a space, specified, e.g., as `Query_Backbone` in the infinity marker annotation table, won't be found later in the processing pipeline.

I worked around this by removing spaces from the infinity marker annotation table, but that's a bit of a hack :)

Best
Martin

**Comment by KyleFerchen** [comment]
Hi Martin,

Thank you for pointing this out. I will add support for spaces in channel names.

Kyle
