### ISSUE TITLE
Files with small amounts of cells cause issues later in the pipeline without helpful error messages

### ISSUE THREAD

**Issue by mgbckr** [KyleFerchen/pyInfinityFlow#2]
FCS files with small cell counts cause issues later in the processing pipeline (e.g., when splitting train/test). It would be nice to catch that when leading the files. Currently, an error about indexing issues is thrown that is not very helpful.

**Comment by KyleFerchen** [comment]
Thank you for pointing this out. 
How many events were in the input file?
Would you mind posting the error message you encountered?
I can try to write a more informative error message.

Best,
Kyle

**Comment by mgbckr** [comment]
It was just one event :D I have to look up the error again. I think you are doing a file check anyway ([Step 2](https://pyinfinityflow.readthedocs.io/en/latest/notebooks/pyInfinityFlow_API_Tutorial.html)) ... maybe catching this there may make sense. Best, Martin
